block: simulator.main_block.4
saes:
  1:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_1_indices.pt
    intervention_multiplier: -1
  2:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_2_indices.pt
    intervention_multiplier: -1
  3:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_3_indices.pt
    intervention_multiplier: -1
  4:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_4_indices.pt
    intervention_multiplier: -1
  5:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_5_indices.pt
    intervention_multiplier: -1
  6:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_6_indices.pt
    intervention_multiplier: -1
  7:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_7_indices.pt
    intervention_multiplier: -1
  8:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_8_indices.pt
    intervention_multiplier: -1
  9:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_9_indices.pt
    intervention_multiplier: -1
  10:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_10_indices.pt
    intervention_multiplier: -1
  11:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_11_indices.pt
    intervention_multiplier: -1
  12:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_12_indices.pt
    intervention_multiplier: -1
  13:
    _target_: rfdiffusion.sae.interventionhook.SAEInterventionHook
    sae_pair_path: null
    sae_non_pair_path: sae-ckpts/picked/patch_topk_expansion_factor16_k64_multi_topkFalse_auxk_alpha0.0lr0.0001_..activations_1200_block4_non_pair/block4_non_pair
    batch_size: 512
    intervention_indices_for_pair: null
    intervention_indices_for_non_pair: /home/wzarzecki/ds_sae_latents_1600x/indices/non_pair/Cytoplasm_13_indices.pt
    intervention_multiplier: -1
