blocks: [
  simulator.main_block.4
]
sae_pair_path: sae-ckpts/RFDiffSAE/patch_topk_expansion_factor32_k256_multi_topkFalse_auxk_alpha0.0_RFDiffSAEactivation_datasets_block4_pair_100_random_per_struct/block4_pair
sae_non_pair_path: sae-ckpts/RFDiffSAE/patch_topk_expansion_factor32_k256_multi_topkFalse_auxk_alpha0.0_RFDiffSAEactivation_datasets_block4_non_pair_100_random_per_struct/block4_non_pair
batch_size: 512